import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Login.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logo}>

        </div>

        <div className={styles.content}>
          <h1>Login</h1>
          <form className={styles.form}>
            <input type="text" placeholder="username"/>
            <input type="password" placeholder="password"/>

            <Link href="/dashboard"><button type="submit">Login</button></Link>
            Read{' '}
            <p>New User?<Link href="/signup"><a>Sign Up</a></Link></p>
          </form>
        </div>
      </main>


    </div>
  )
}
