import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Login.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logo}>

        </div>

        <div className={styles.contentSignup}>
        <h1>Sign Up</h1>
        <form className={styles.formSignup}>
            <input type="text" placeholder="Full Name"/>
            <input type="email" placeholder="Email"/>
            <input type="number" placeholder="Phone Number"/>
            <input type="date" placeholder="Date of Birth"/>
            <input type="text" placeholder="username"/>
            <input type="password" placeholder="password"/>
            <input type="password" placeholder="confirm password"/>
            <button type="submit"> Sign Up</button>
            <p>Existing User?<Link href="/"><a>Login</a></Link></p>

          </form>
        </div>
      </main>


    </div>
  )
}
