import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Login.module.css'
import Link from 'next/link'
import { useState } from 'react';
import Router from "next/router"

export default function Home() {

  const [firstname, setFirstname] = useState('')
  const [lastname, setLastname] = useState('')
  const [email, setEmail] = useState('')
  const [phone, setPhone] = useState(0)
  const [date, setDate] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')


  const createUser = async(firstname, lastname, email, phone, date, password) => {
    const newUser = {firstname, lastname, email, phone, dob: date, password}
    console.log(newUser)
    const res = await fetch(`http://localhost:7000/api/v2/spendingApp/auth/signUp`,{
            method: 'POST',
            headers: {
                'Content-type' : 'application/json',
            },
            body: JSON.stringify(newUser),
        })

    return res;
    }

  const onSubmit = async(e) => {
        e.preventDefault()
        const user = await createUser(firstname, lastname, email, phone, date, password)
        console.log(user)
        if(user.status == 201){
          Router.push('/');
        }

        //If successful, show successful, if not show error
        //re route to login page
        //
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logo}>

        </div>

        <div className={styles.contentSignup}>
        <h1>Sign Up</h1>

        <form className={styles.formSignup} onSubmit={onSubmit}>

            <input type="text" required onChange={(e) => setFirstname(e.target.value)} placeholder="First Name"/>
            <input type="text" required onChange={(e) => setLastname(e.target.value)} placeholder="Last Name"/>
            <input type="email" required onChange={(e) => setEmail(e.target.value)} placeholder="Email"/>
            <input type="number" required onChange={(e) => setPhone(Number(e.target.value))} placeholder="Phone Number"/>
            <input type="date" required onChange={(e) => setDate(e.target.value)} placeholder="Date of Birth"/>
            <input type="password" required onChange={(e) => setPassword(e.target.value)} placeholder="password"/>
            <input type="password" required onChange={(e) => setConfirmPassword(e.target.value)} placeholder="confirm password"/>

            <button type="submit"> Sign Up</button>

            <p>Existing User?<Link href="/"><a>Login</a></Link></p>

          </form>
        </div>
      </main>


    </div>
  )
}
